### ISSUE TITLE
Trade in chart indicator

### ISSUE THREAD

**Issue by eckbertg** [DominikBritz/NinjaTrader-indicators-strategies#3]
Hi Dominik, 

Congratulations on your indicator. It makes placing orders so easy and quickly. There is one aspect in Ninja which is very irritating and that is there FIFO trade management. 

This is especially annoying when one wants to scale in positions and Ninja averages then all positions. So as an example on the ES futures I will open a position at 4410. I want to add a second position at 4415. Once the second position is opened Ninja will show 2 positions at the average price of 4412,5. Is there anyway of showing the scale in positions as separate unique entries. This would be a great addition to your indicator. 

I hope this makes sense to you. 

Kind Regards Eckbert

**Comment by DominikBritz** [comment]
Thanks! I have no plans to add this functionality, sorry.
