### ISSUE TITLE
Indicators for ICT strategy in NT8

### ISSUE THREAD

**Issue by Rcmining** [DominikBritz/NinjaTrader-indicators-strategies#8]
Hi Dominik

your work is excellent on all Indicators that you have done for NT8.
Could you mind , if you can make any indicators for strategy of ICT (https://www.youtube.com/@InnerCircleTrader/videos), because only there are many of them but in TeamViewer, _like Kill-zones, Breakers, and others.
The Kill-zones will be great, is like the "entrance door" if you would wish.
Best regards
Rommel Castro

**Comment by DominikBritz** [comment]
I'm not an ICT trader and have no idea what you are talking about :-D I'm sorry but I won't spend my free time on things that I won't use.

**Comment by Rcmining** [comment]
Hi Dominik

Thanks for your answer,
And your attention.
Good luck

Rommel castro
